version: '3'
volumes:
  postgres_data:
    driver: local
  mysql_data: null
services:
  postgres:
    image: postgres
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - backend
  keycloak:
    image: 'quay.io/keycloak/keycloak:legacy'
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      #KEYCLOAK_USER: admin
      #KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
        - backend
  mysql:
    image: mysql
    volumes:
      - 'mysql_data:/var/lib/mysql'
    environment:
      MYSQL_DATABASE: fitnessapp
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: fitness
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    networks:
      - backend
  app:
    build: 
        context: resource-server
        dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - '8081:8081'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://mysql/fitnessapp'
      - 'KEYCLOAK_SERVER=http://keycloak:8080'
    depends_on:
      - mysql
networks:
  backend:
    driver: bridge
