spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost/fitnessapp}
    username: fitness
    password: password
    initialization-mode: always

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.server}/auth/realms/master
          jwk-set-uri: ${keycloak.server}/auth/realms/master/protocol/openid-connect/certs

server:
  port: 8081

keycloak:
  server: ${KEYCLOAK_SERVER}

logging:
  level:
    org.spring.framework: debug

